import type { ServiceItem, VtuFlowConfig } from "./types";

export const currentUser = {
  name: "James Okon",
  initials: "JO",
  email: "james.okon@tennetdigital.ng",
  role: "Verification Agent",
  memberSince: "March 2025",
  reference: "usr_6a8ea6983287a",
  walletBalance: 24500,
  accounts: [
    { bank: "Wema Bank", number: "9816530408", label: "Naira settlement" },
    { bank: "Providus Bank", number: "9606028341", label: "Virtual account" },
  ],
};

export const services: ServiceItem[] = [
  // VTU
  {
    slug: "airtime",
    name: "Airtime top-up",
    category: "vtu",
    flow: "vtu",
    description: "Recharge any Nigerian network instantly from your wallet.",
    price: 0,
    icon: "phone",
  },
  {
    slug: "data",
    name: "Data bundles",
    category: "vtu",
    flow: "vtu",
    description: "Buy data plans across MTN, Airtel, Glo, and 9mobile.",
    price: 0,
    icon: "wifi",
  },
  {
    slug: "bill",
    name: "Bill payment",
    category: "vtu",
    flow: "vtu",
    description: "Settle electricity and utility bills against a meter number.",
    price: 0,
    icon: "zap",
  },
  {
    slug: "tv-cable",
    name: "TV cable subscription",
    category: "vtu",
    flow: "vtu",
    description: "Renew DStv, GOtv, and Startimes subscriptions by smartcard.",
    price: 0,
    icon: "tv",
  },
  // Verification
  {
    slug: "nin",
    name: "NIN verification",
    category: "verification",
    flow: "lookup",
    description: "Confirm a National Identification Number against demographic records.",
    price: 150,
    icon: "id-badge",
  },
  {
    slug: "bvn",
    name: "BVN verification",
    category: "verification",
    flow: "lookup",
    description: "Match a Bank Verification Number and pull enrolment details.",
    price: 170,
    icon: "landmark",
  },
  // Records & modification
  {
    slug: "nin-modification",
    name: "NIN modification",
    category: "records",
    flow: "request",
    description: "Submit a correction request for name, DOB, or phone fields.",
    price: 2500,
    icon: "file-edit",
  },
  {
    slug: "nin-validation",
    name: "NIN validation",
    category: "records",
    flow: "lookup",
    description: "Cross-check a NIN slip against the live enrolment register.",
    price: 300,
    icon: "check-check",
  },
  {
    slug: "nin-enrollment",
    name: "NIN enrollment",
    category: "records",
    flow: "request",
    description: "Register a new applicant for a National Identification Number.",
    price: 3500,
    icon: "user-plus",
  },
  {
    slug: "bvn-modification",
    name: "BVN modification",
    category: "records",
    flow: "request",
    description: "Update BVN demographic fields through the enrolment partner.",
    price: 3000,
    icon: "file-cog",
  },
  {
    slug: "bvn-retrieval",
    name: "BVN retrieval",
    category: "records",
    flow: "lookup",
    description: "Recover a lost or forgotten BVN linked to a phone number.",
    price: 500,
    icon: "file-search",
  },
  {
    slug: "bvn-central-risk",
    name: "BVN central risk check",
    category: "records",
    flow: "lookup",
    description: "Screen a BVN against the central fraud and risk registry.",
    price: 800,
    icon: "shield-alert",
  },
  {
    slug: "bvn-onboarding",
    name: "BVN onboarding",
    category: "records",
    flow: "request",
    description: "Enrol a first-time customer into the BVN scheme end to end.",
    price: 2000,
    icon: "user-check",
  },
  {
    slug: "self-service-delink",
    name: "Self-service delink",
    category: "records",
    flow: "request",
    description: "Unlink a phone number or account mistakenly tied to a BVN.",
    price: 1000,
    icon: "unlink",
  },
  {
    slug: "npc-attestation",
    name: "NPC attestation",
    category: "records",
    flow: "request",
    description: "Issue a National Population Commission attestation letter.",
    price: 1200,
    icon: "file-check-2",
  },
  {
    slug: "personalization",
    name: "Personalization",
    category: "records",
    flow: "request",
    description: "Encode and personalize a physical ID card for collection.",
    price: 2500,
    icon: "search",
  },
  {
    slug: "affidavit",
    name: "Affidavit",
    category: "records",
    flow: "request",
    description: "Generate a sworn affidavit for name or age declaration.",
    price: 3500,
    icon: "scale",
  },
  {
    slug: "ipe-clearance",
    name: "IPE clearance",
    category: "records",
    flow: "request",
    description: "Clear an in-process enrolment flagged for manual review.",
    price: 1500,
    icon: "file-badge",
  },
  // Registration
  {
    slug: "tin-registration",
    name: "Register TIN",
    category: "registration",
    flow: "request",
    description: "Issue a Tax Identification Number for an individual or entity.",
    price: 1000,
    icon: "receipt",
  },
  {
    slug: "cac-registration",
    name: "Register CAC",
    category: "registration",
    flow: "request",
    description: "Register a business name with the Corporate Affairs Commission.",
    price: 15000,
    icon: "briefcase",
  },
  {
    slug: "print-tin",
    name: "Print TIN",
    category: "registration",
    flow: "lookup",
    description: "Reprint a TIN certificate for an already-registered entity.",
    price: 500,
    icon: "printer",
  },
];

export const vtuConfig: Record<string, VtuFlowConfig> = {
  airtime: {
    recipientLabel: "Phone number",
    recipientPlaceholder: "080XXXXXXXX",
    mode: "amount",
    presetAmounts: [100, 200, 500, 1000, 2000],
    providers: ["MTN", "Airtel", "Glo", "9mobile"],
  },
  data: {
    recipientLabel: "Phone number",
    recipientPlaceholder: "080XXXXXXXX",
    mode: "plan",
    plans: [
      { label: "1GB · 30 days", price: 350 },
      { label: "2GB · 30 days", price: 600 },
      { label: "5GB · 30 days", price: 1500 },
      { label: "10GB · 30 days", price: 3000 },
    ],
    providers: ["MTN", "Airtel", "Glo", "9mobile"],
  },
  bill: {
    recipientLabel: "Meter number",
    recipientPlaceholder: "Enter meter number",
    mode: "amount",
    presetAmounts: [1000, 2000, 5000, 10000],
  },
  "tv-cable": {
    recipientLabel: "Smartcard number",
    recipientPlaceholder: "Enter smartcard number",
    mode: "plan",
    plans: [
      { label: "DStv Compact · 1 month", price: 19000 },
      { label: "GOtv Max · 1 month", price: 8500 },
      { label: "Startimes Nova · 1 month", price: 1900 },
    ],
  },
};

